In [5]:
!pip install faiss-cpu
!pip install sentence-transformers

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable


In [6]:
import pandas as pd
pd.set_option('display.max_colwidth',100)


In [7]:
df=pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [10]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [14]:
from sentence_transformers import SentenceTransformer
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df['text'].tolist())
print(vectors.shape)

C:\Users\honey\AppData\Roaming\Python\Python312\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


(8, 768)


In [15]:
vectors

array([[-0.00247395,  0.03626722, -0.0529046 , ..., -0.09152357,
        -0.03970002, -0.0433049 ],
       [-0.03357267,  0.00980518, -0.0325013 , ..., -0.05165466,
         0.02245887, -0.03156183],
       [-0.01865321, -0.04051314, -0.01235387, ...,  0.00610584,
        -0.07179642,  0.02773852],
       ...,
       [-0.00066457,  0.04252126, -0.05645509, ...,  0.0131547 ,
        -0.03183571, -0.04357664],
       [-0.03317155,  0.03252454, -0.02484839, ...,  0.01174421,
         0.05747125,  0.00571022],
       [-0.00166396,  0.00413826, -0.04597082, ...,  0.0200853 ,
         0.05656241, -0.00161596]], dtype=float32)

In [ ]:

from sentence_transformers import SentenceTransformer

In [11]:
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)
vectors.shape

C:\Users\honey\AppData\Roaming\Python\Python312\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


(8, 768)

In [18]:
# Create Faiss VEctor

In [19]:
dim=vectors.shape[1]
dim

768

In [20]:
import faiss
index=faiss.IndexFlatL2(dim)

In [21]:
index.add(vectors)

In [22]:
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001D56C203720> >

In [23]:
# search_query = "I want to buy a polo t-shirt"
# # search_query = "looking for places to visit during the holidays"
# # search_query = "An apple a day keeps the doctor away"
# vec = encoder.encode(search_query)
# vec.shape

In [24]:
search_query="I want to buy a polo t-shirt"
vec=encoder.encode(search_query)
vec.shape

(768,)

In [25]:
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [26]:
distances,I=index.search(svec,k=2)

In [27]:
I

array([[3, 2]], dtype=int64)

In [28]:
df.loc[[3,2]]

text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion

In [29]:
index.search(svec,k=2)

(array([[1.3844838, 1.4039094]], dtype=float32), array([[3, 2]], dtype=int64))

In [30]:
search_query="An apple a day keeps the doctor away"
vec2=encoder.encode(search_query)
vec.shape

(768,)

In [31]:
import numpy as np
svec2 = np.array(vec).reshape(1,-1)
svec2.shape

(1, 768)

In [32]:
index.search(svec,k=2)

(array([[1.3844838, 1.4039094]], dtype=float32), array([[3, 2]], dtype=int64))

In [33]:
df.loc[[1,0]]

text category
1  Fruits, whole grains and vegetables helps control blood pressure   Health
0                     Meditation and yoga can improve mental health   Health

In [34]:
search_query="looking for places to visit during the holidays"
vec3=encoder.encode(search_query)
vec3.shape

(768,)

In [35]:
import numpy as np
svec3 = np.array(vec).reshape(1,-1)
svec3.shape

(1, 768)

In [36]:
index.search(svec3,k=2)

(array([[1.3844838, 1.4039094]], dtype=float32), array([[3, 2]], dtype=int64))